#! /bin/bash

flag=$1
user=$2
repo=$3

if [ "$flag" == "--user" ] || [ "$flag" == "-u" ]; then
    if [ $# -lt 3 ]; then
        printf "The user flag was called. You must include both user and repo.\n"
        printf "User: "
        read -r user
        printf "Repo: "
        read -r repo
    fi
else 
    repo=$1 
    user="edwinmoradian90"   
fi
git clone https://github.com/"$user"/"$repo"


