#!/bin/bash

view="View"
type="functional"

for arg in "$@"
do 
    if [ "$arg" = "--class" ]  || [ "$arg" = "-c" ]; then
        type="class"
    fi
done

if [ "$#" > 1  ]; then
    for arg in "$@"
    do
        mkdir "$arg" && cd "$arg"
        if [ "$type" = "class" ]; then
            rcc "$arg" "$arg$view"
        else
            rfc "$arg" "$arg$view"
        fi
        cd ..
    done
fi