#! /bin/bash

commit="$1"
location="$2"

git add .

if [ "$commit" ]
then 
    git commit -m "$commit" 
else
    echo "Commit message: "
    location="$1"
    read commit 
    git commit -m "$commit"
fi

if [ "$location" ]
then
    git push origin "$location"
else 
    echo "Branch name: "
    read location
    if [ -z "$location" ];then 
        echo "Branch was left empty. Defaulting to master branch."
        git push origin master
    else
        git push origin "$location"
    fi
fi
