#! /bin/bash 

component_name=$1
component_ext="jsx"

if [ $# -lt 1 ]; then
    printf "Component name: "
    read -r component_name
fi 

if [ "$(pkg-check typescript)" ]; then
    component_ext="tsx"
fi

for component_name in "$@"; do
    echo "React class component '$component_name' generated."
    printf "import React, { Component } from 'react'

class %s extends Component {
    render() {
        return (
            <div className='%s'>
                %s
            </div>
        )    
    }
} 

export default %s" "$component_name" "$component_name" "$component_name" "$component_name">> "$component_name"."$component_ext"
done